(require 'cl-ppcre)

(defun sum-muls (f use-do)
  (let ((enabled t)
        (sum 0))
    (labels ((fun (str)
               (cl-ppcre:register-groups-bind (nil en dis mul (#'parse-integer a b) rest)
                   ("((do\\(\\))|(don't\\(\\))|(mul\\((\\d+),(\\d+)\\)))(.*)" str)
                 (cond ((and use-do (or en dis)) (setf enabled (not (not en))))
                       (mul (when enabled (incf sum (* a b))))
                       (t nil))
                 (when (or en dis mul) (fun rest)))))
      (fun (reduce (lambda (a b) (concatenate 'string a b)) (uiop:read-file-lines f))))
    sum))

(assert (eq (sum-muls "test.txt" nil) 161))
(print (sum-muls "input.txt" nil))
(assert (eq (sum-muls "test2.txt" t) 48))
(print (sum-muls "input.txt" t))
