(load "../aoc")
(load "board")

(defun count-rolls-with-fewer-than-4-neighbors (file)
  (let ((b (read-board-file file))
        (acc 0))
    (labels ((roll-at-p (pos) (eq (at pos b) #\@))
             (count-if-roll-with-fewer-than-4-neighbors (pos c)
               (when (eq c #\@)
                 (when (< (length (remove-if-not #'roll-at-p (neighbor-positions pos (board-dimensions b)))) 4)
                   (incf acc)))))
      (for-each-pos-on-board #'count-if-roll-with-fewer-than-4-neighbors b)
      acc)))

(defun count-rolls-that-can-be-removed (file)
  (let ((b (read-board-file file))
        (run-again)
        (acc 0))
    (labels ((roll-at-p (pos) (eq (at pos b) #\@))
             (roll-with-fewer-than-4-neighbors (pos)
               (and (roll-at-p pos)
                    (< (length (remove-if-not #'roll-at-p (neighbor-positions pos (board-dimensions b)))) 4)))
             (count-and-remove-if-fewer-than-4-neighbors (pos c)
               (declare (ignore c))
               (when (roll-with-fewer-than-4-neighbors pos)
                 (set-at #\. pos b)
                 (incf acc)
                 (setf run-again t)))
             (f ()
               (setf run-again nil)
               (for-each-pos-on-board #'count-and-remove-if-fewer-than-4-neighbors b)
               (when run-again (f))))
      (f))
    acc))

(aoc (lambda (file) (count-rolls-with-fewer-than-4-neighbors file)) 13
     (lambda (file) (count-rolls-that-can-be-removed file)) 43)
