(load "board")

(defun fill-in-distance (pos curdir sb b)
  (mapc (lambda (dir)
          (let* ((adj-pos (+ pos dir))
                 (score (+ (at pos sb)
                           (cond ((eq (at pos b) #\E) 1)
                                 ((and (eq (at adj-pos b) #\S) (not (eq curdir -1))) 1001)
                                 ((= dir curdir) 1)
                                 (t 1001)))))
            (when (and (inside-board adj-pos b)
                       (not (eq (at adj-pos b) #\#))
                       (< score (or (at adj-pos sb) 9999999999)))
              (set-at score adj-pos sb)
              (fill-in-distance adj-pos dir sb b))))
        *north-east-south-west*))

(defun lowest-reindeer-score (file)
  (let* ((b (read-board-file file))
         (start (car (find-eq #\S b)))
         (end (car (find-eq #\E b)))
         (sb (make-empty-board (board-dimensions b))))
    (set-at 0 end sb)
    (fill-in-distance end #C(0 1) sb b)

    (print-board b)
    (flet ((print-char (pos c)
             (when (zerop (realpart pos)) (terpri))
             (format t "~7d" (or c -1))))
      (for-each-pos-on-board #'print-char sb))

    (at start sb)))

(assert (= (lowest-reindeer-score "test.txt") 7036))
(assert (= (lowest-reindeer-score "test2.txt")  11048))
;;(assert (= (print (lowest-reindeer-score "input.txt")) 105508))
