(load "board")

(defun fill-score-board (pos dir sb b)
  (flet ((wall-p (pos) (eq (at pos b) #\#))
         (end-p (pos) (eq (at pos b) #\E))
         (step-in-dir (dir) (+ pos dir)))
    (let* ((current-cost (at pos sb))
           (pos-to-follow
             (mapcan (lambda (new-pos)
                       (let* ((step-cost (if (= (- new-pos pos) dir) 1 1001))
                              (new-cost (+ current-cost step-cost))
                              (existing-cost (at new-pos sb)))
                         (unless (and existing-cost (< existing-cost new-cost))
                           (set-at new-cost new-pos sb)
                           (list new-pos))))
                     (remove-if #'wall-p (mapcar #'step-in-dir *north-east-south-west*)))))
      (mapcar (lambda (new-pos) (fill-score-board new-pos (- new-pos pos) sb b))
              (remove-if #'end-p pos-to-follow)))))

;; (defun cost (path)
;;   (labels ((f (p dir)
;;              (if (< (length p) 2)
;;                  0
;;                  (+ (if (= (+ (car p) dir) (cadr p)) 1 1001)
;;                     (f (cdr p) (- (cadr p) (car p)))))))
;;     (f (reverse path) 1)))

;; (let ((min-cost))
;;   (defun paths-to (end cost path b)
;;     (flet ((d0 (list) (- (cadr list) (car list))))
;;       (incf cost (if (cdr path)
;;                      (if (= (d0 path)
;;                             (if (cddr path)
;;                                 (d0 (cdr path))
;;                                 1)) ;; Start in eastern dir
;;                          1 1001)
;;                      0)))
;;     (when (or (not min-cost) (< cost min-cost))
;;       (if (= end (car path))
;;           (progn
;;             (print path)
;;             (print (cost path))
;;             (setf min-cost (min cost (or min-cost cost)))
;;             (list path))

(defun lowest-reindeer-score (file)
  (let* ((b (read-board-file file))
         (start (car (find-eq #\S b)))
         (end (car (find-eq #\E b)))
         (sb (make-empty-board (board-dimensions b))))
    (set-at 0 start sb)
    (fill-score-board start 1 sb b)

    (flet ((print-char (pos c)
             (when (zerop (realpart pos)) (terpri))
             (format t "~7d" (or c -1))))
      (for-each-pos-on-board #'print-char sb))

    (at end sb)))

(assert (= (lowest-reindeer-score "test.txt") 7036))
(assert (= (lowest-reindeer-score "test2.txt")  11048))
(print (lowest-reindeer-score "input.txt"))
